=== JCBurnside/JCBurnside.github.io/robots.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
<xs:element name="robots" type="robotsType"/>
<xs:complexType name="robotType">
	<xs:all>
		<xs:element type="xs:string" name="name"/>
		<xs:element type="xs:string" name="description"/>
		<xs:element type="xs:string" name="imgPath"/>
		<xs:element type="xs:decimal" name="price"/>
		<xs:element type="xs:string" name="tags"/>
	</xs:all>
	<xs:attribute type="xs:string" name="class"/>
</xs:complexType>

<xs:complexType name="robotsType">
	<xs:sequence>
		<xs:element name="robot" type="robotType" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>



</xs:schema>

=== JCBurnside/JCBurnside.github.io/robots.xml
<?xml version="1.0" encoding="UTF-8"?>
<robots xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="jcburnside.github.io robots.xsd">
	<robot>
		<name>The destroyer</name>
		<description>string</description>
		<imgPath>string</imgPath>
		<price>3000.98</price>
		<tags>string</tags>
	</robot>
	<robot>
		<name>The destroyer</name>
		<description>string</description>
		<imgPath>string</imgPath>
		<price>3000.98</price>
		<tags>string</tags>
	</robot>
	<robot>
		<name>The destroyer</name>
		<description>string</description>
		<imgPath>string</imgPath>
		<price>3000.98</price>
		<tags>string</tags>
	</robot>
	<robot>
		<name>The destroyer</name>
		<tags>string</tags>
		<description>string</description>
		<imgPath>string</imgPath>
		<price>3000.98</price>
	</robot>
	<robot>
		<name>The destroyer</name>
		<description>string</description>
		<imgPath>string</imgPath>
		<price>3000.98</price>
		<tags>string</tags>
	</robot>
	<robot>
		<name>The destroyer</name>
		<description>string</description>
		<imgPath>string</imgPath>
		<price>3000.98</price>
		<tags>string</tags>
	</robot>
</robots>
